### ISSUE TITLE
mbstring.func_overload

### ISSUE THREAD

**Issue by paragonie-scott** [ezimuel/phpcrypto#4]
`php -dmbstring.func_overload=7 test.php`

``` php
<?php
var_dump(strlen("\xF0\x9D\xA5\xB3"));
```

Guess what this produces.

---

Using `strlen()` and `substr()` for crypto can be dangerous, especially since you work with raw binary.

**Comment by ezimuel** [comment]
@paragonie-scott right, I should use mb_strlen() and mb_substr() for binary data. I'll fix this shortly. Thanks again for your suggestion!

**Comment by ezimuel** [comment]
@paragonie-scott I fixed in master.

**Comment by paragonie-scott** [comment]
:+1:
